# Generated by Django 2.2.13 on 2021-03-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingevent',
            name='log_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
