# Generated by Django 2.2.13 on 2021-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dag', '0002_loggingevent_log_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingevent',
            name='log_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
